import React,{useState} from 'react';
import {ArrowLeft,ArrowRight,Download,Loader2,Sparkles} from 'lucide-react';
import type {Project,DifficultyLevel,PracticeMode} from '../types';
import {computeUnlocks} from '../services/practiceMode';
import {allowsOnlineAI,downloadText} from '../services/projectWorkflow';
import {externalPacket,MAX_BUILTIN_QUESTIONS} from '../services/generationPrompt';
import {generationObjectivePlan,objectiveCoverage} from '../services/objectiveCoverage';

type Props={project:Project;onGenerate:(configured:Project)=>void;onUpdate:(p:Project)=>void;onBack:()=>void;onMaterials:()=>void;onResume:()=>void;onImport:()=>void;loading:boolean;disabled:boolean;signedIn:boolean;availability:{available:boolean;reason:string};onCheckAccess:()=>void;error:string|null};
export default function ExamGeneratorPanel({project,onGenerate,onUpdate,onBack,onMaterials,onResume,onImport,loading,disabled,signedIn,availability,onCheckAccess,error}:Props){
  const [count,setCount]=useState(Math.max(1,Math.min(MAX_BUILTIN_QUESTIONS,project.activeExam.questionCount||20)));
  const [duration,setDuration]=useState(project.activeExam.durationMinutes||30);
  const [difficulty,setDifficulty]=useState<DifficultyLevel>(project.activeExam.difficulty==='standard'?'standard':'hard');
  const [mode,setMode]=useState<PracticeMode>(project.activeExam.practiceMode||'balanced');
  const [ids,setIds]=useState(project.activeExam.selectedSectionIds||project.blueprint.map(s=>s.id));
  const [packetError,setPacketError]=useState(''),[packetReady,setPacketReady]=useState(false);
  const [includeSources,setIncludeSources]=useState(true);
  const configured={...project,activeExam:{...project.activeExam,questionCount:count,durationMinutes:duration,difficulty,practiceMode:mode,selectedSectionIds:ids}};
  const unlocks=computeUnlocks(project.examHistory);
  const plan=generationObjectivePlan(configured,ids,count);
  const coverage=project.registry?objectiveCoverage(project.registry,(project.savedExams||[]).filter(e=>!e.retired).flatMap(e=>e.questions),project.examHistory):[];
  const untested=plan.filter(id=>coverage.find(r=>r.id===id)?.assessed===0).length;
  const active=project.activeExam.status==='active'&&project.activeExam.questions.length>0;
  const hasKnowledge=!project.registry||plan.length>0;
  const hasSources=!!project.registry||project.learningObjectivesFiles.length>0||project.blueprint.some(s=>ids.includes(s.id)&&s.files.some(f=>f.content.trim()));
  const reason=disabled?'Use this tab to edit before generating.':active?'Finish or save your current attempt before creating another.':!ids.length?'Choose at least one topic below, or add topics in Study materials.':!hasKnowledge?'These topics contain performance skills; select a written knowledge topic.':!hasSources?'Add learning objectives or study materials first.':!signedIn?'Sign in to generate with Gemini. You can still prepare an exam with your own AI below.':!availability.available?availability.reason:!allowsOnlineAI(project)?'Enable Gemini for this project to generate here.':'';
  return <div className="space-y-6 print:hidden">
    <button onClick={onBack} className="action-quiet"><ArrowLeft className="w-4 h-4"/>Back to exams</button>
    <div><h2 className="text-3xl font-semibold tracking-tight">Generate an exam</h2><p className="text-slate-600 mt-2 leading-relaxed">New questions follow your objective plan and study materials. A separate AI check solves them without seeing the proposed answers; unsupported, ambiguous or trivial drafts are excluded before saving.</p></div>
    <section className="bg-white border border-slate-200 rounded-2xl p-5 sm:p-7 space-y-6">
      <div className="grid sm:grid-cols-3 gap-5">
        <label className="text-sm font-medium">Questions<select aria-label="Number of questions" className="w-full mt-2 border rounded-lg px-3 py-3 bg-white text-base" value={count} disabled={loading} onChange={e=>setCount(Number(e.target.value))}>{[...new Set([5,10,15,20,count])].sort((a,b)=>a-b).map(n=><option key={n} value={n}>{n} questions</option>)}</select></label>
        <label className="text-sm font-medium">Time limit<input aria-label="Time limit in minutes" className="w-full mt-2 border rounded-lg px-3 py-3 text-base" type="number" min="1" max="240" value={duration} disabled={loading} onChange={e=>setDuration(Math.min(240,Math.max(1,Number(e.target.value)||1)))}/><span className="text-xs text-slate-500 font-normal">Minutes, starting when you begin</span></label>
        <label className="text-sm font-medium">Difficulty<select aria-label="Difficulty" className="w-full mt-2 border rounded-lg px-3 py-3 bg-white text-base" value={difficulty} disabled={loading} onChange={e=>setDifficulty(e.target.value as DifficultyLevel)}><option value="standard">Standard</option><option value="hard">Hard</option></select></label>
      </div>
      <fieldset disabled={loading}><legend className="font-medium mb-3">What would you like to cover?</legend><div className="flex flex-wrap items-center justify-between gap-3 mb-3 text-sm"><span className="text-slate-600">{ids.length} of {project.blueprint.length} topics selected</span><button className="text-blue-700 hover:underline" onClick={()=>setIds(ids.length===project.blueprint.length?[]:project.blueprint.map(s=>s.id))}>{ids.length===project.blueprint.length?'Clear selection':'Select all'}</button></div><div className="grid sm:grid-cols-2 gap-2 max-h-64 overflow-auto pr-1">{project.blueprint.map(s=><label key={s.id} className={`flex items-start gap-3 border rounded-lg p-3 text-sm cursor-pointer ${ids.includes(s.id)?'border-blue-200 bg-blue-50/50':'border-slate-200'}`}><input type="checkbox" className="mt-0.5 accent-blue-600" checked={ids.includes(s.id)} onChange={e=>setIds(e.target.checked?[...ids,s.id]:ids.filter(x=>x!==s.id))}/><span>{s.title}<span className="block text-xs text-slate-500 mt-1">{s.files.length} source files</span></span></label>)}</div></fieldset>
      <div className="border-t pt-4 space-y-3"><label className="block text-sm font-medium">Practice focus<select aria-label="Practice focus" disabled={loading} value={mode} onChange={e=>setMode(e.target.value as PracticeMode)} className="w-full mt-2 border rounded-lg p-3 bg-white font-normal"><option value="balanced">Balanced coverage</option><option value="focused" disabled={!unlocks.focused.unlocked}>More practice on missed answers{!unlocks.focused.unlocked?' (complete an exam first)':''}</option><option value="targeted" disabled={!unlocks.targeted.unlocked}>Missed answers first, then untested objectives{!unlocks.targeted.unlocked?' (complete an exam first)':''}</option></select></label><p className="text-sm text-slate-600">Wrong and blank answers in completed exams both guide future practice. New cases test the same knowledge without repeating the question. Each set uses up to six topics so their complete chapters can be checked; remaining misses and topics stay in the queue for later sets.</p>{plan.length>0&&<details className="text-sm rounded-lg bg-slate-50 p-3"><summary className="cursor-pointer font-medium">Planned coverage: {plan.length} objectives · {untested} not yet tested</summary><ul className="mt-3 space-y-2 max-h-48 overflow-auto">{plan.map(id=><li key={id}><span className="font-medium">{id}</span> · {project.registry!.objectives[id].text || id}</li>)}</ul><p className="mt-3 text-slate-500">One question samples a specific part of an objective. Examination and procedure performance requires direct practice.</p></details>}</div>
      <details className="border-t pt-4"><summary className="cursor-pointer font-medium text-sm">AI settings</summary><div className="mt-4 space-y-4"><label className="flex gap-3 text-sm text-slate-600"><input type="checkbox" className="mt-1" disabled={disabled||loading} checked={allowsOnlineAI(project)} onChange={e=>onUpdate({...project,allowOnlineAI:e.target.checked})}/><span>Use Gemini for this project. Selected study material is sent when you generate questions or use the tutor.</span></label></div></details>
      <div className="border-t pt-5"><p className="text-sm text-slate-500 mb-4">Up to 20 questions per set. Wording overlap is checked; similarity of clinical concepts still needs review. Writing and checking use separate Gemini requests. If some questions fail checking, the saved set is shorter and those objectives remain gaps.</p>{reason&&<div className="text-sm bg-amber-50 text-amber-900 border border-amber-200 rounded-lg p-3 mb-4">{reason} {(!hasSources||!project.blueprint.length)&&<button onClick={onMaterials} className="underline ml-1">Add study materials</button>}{active&&<button onClick={onResume} className="underline ml-1">Continue current exam</button>}{signedIn&&!availability.available&&<button className="underline ml-2" onClick={onCheckAccess}>Check again</button>}{signedIn&&availability.available&&!allowsOnlineAI(project)&&<button className="underline ml-2" disabled={disabled} onClick={()=>onUpdate({...project,allowOnlineAI:true})}>Enable Gemini</button>}{!signedIn&&<a className="underline ml-1" href={`/?signin=1&localProject=${encodeURIComponent(project.id)}`}>Sign in</a>}</div>}{error&&error!==reason&&<p role="alert" className="text-sm bg-red-50 text-red-800 rounded-lg p-4 mb-4">{error}</p>}<button className="action-primary w-full sm:w-auto" disabled={!!reason||loading} onClick={()=>onGenerate(configured)}>{loading?<Loader2 className="w-4 h-4 animate-spin"/>:<Sparkles className="w-4 h-4"/>}{loading?'Generating your exam…':`Generate ${count} questions`}</button>{loading&&<p role="status" className="mt-3 text-sm text-slate-600">This can take a few minutes. Keep this tab open; your current exams are safe.</p>}</div>
    </section>
    <details open={!signedIn||!availability.available||!!error||undefined} className="rounded-xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer font-medium">Prefer to use ChatGPT, Claude or another AI?</summary><div className="mt-4 space-y-4 text-sm text-slate-600"><p>Use the settings above. These steps give your AI the same objectives, source material and writing instructions used by the built-in generator.</p><ol className="list-decimal pl-5 space-y-3"><li><strong className="text-slate-900 font-medium">Download the instructions and materials.</strong> The file also identifies previous practice questions to avoid.</li><li><strong className="text-slate-900 font-medium">Attach the file to your AI chat.</strong> Say: “Follow the attached instructions and return a new exam as a JSON file.”</li><li><strong className="text-slate-900 font-medium">Bring the result back.</strong> Choose Import an exam and select the JSON file your AI returns.</li></ol><label className="flex gap-2"><input type="checkbox" checked={includeSources} onChange={e=>setIncludeSources(e.target.checked)}/>Include study material in the file</label>{!includeSources&&<p>Attach the original study files to your AI yourself.</p>}{packetError&&<p role="alert" className="text-red-700">{packetError}</p>}<div className="flex flex-wrap gap-3"><button className="action-secondary" disabled={!ids.length||!hasSources} onClick={()=>{try{downloadText(`${project.name}-AI-instructions.md`,externalPacket(configured,includeSources),'text/markdown');setPacketError('');setPacketReady(true);}catch(e){setPacketError((e as Error).message);}}}><Download className="w-4 h-4"/>Download AI instructions</button><button className="action-quiet" onClick={onImport}>Import the result <ArrowRight className="w-4 h-4"/></button></div>{packetReady&&<p role="status" className="text-blue-800">Downloaded. Attach the .md file to your AI chat, then import its returned exam here.</p>}</div></details>
  </div>;
}
