import React,{useMemo,useState} from 'react';
import type {Project} from '../types';
import {objectiveCoverage} from '../services/objectiveCoverage';

export default function ObjectiveCoveragePanel({project,onGenerate}:{project:Project;onGenerate:()=>void}) {
  const [filter,setFilter]=useState('all'),[search,setSearch]=useState('');
  const rows=useMemo(()=>project.registry?objectiveCoverage(project.registry,(project.savedExams || []).filter(e=>!e.retired).flatMap(e=>e.questions),project.examHistory):[],[project.registry,project.savedExams,project.examHistory]);
  if(!project.registry)return null;
  const knowledge=rows, skills=rows.filter(r=>r.skill);
  const visible=rows.filter(r=>(filter==='all'||filter==='untested'&&r.assessed===0||filter==='missed'&&r.missed>0||filter==='gaps'&&r.available===0||filter==='skills'&&r.skill)&&`${r.id} ${r.text} ${r.topic} ${r.bucket}`.toLowerCase().includes(search.toLowerCase()));
  const buckets=[...new Set(visible.map(r=>r.bucketId))];
  return <section className="mb-7 rounded-2xl border border-slate-200 bg-white p-5 sm:p-7 space-y-5">
    <div className="flex flex-wrap justify-between gap-4"><div><h3 className="text-xl font-semibold tracking-tight">Objective coverage</h3><p className="mt-2 text-sm text-slate-600 max-w-3xl leading-relaxed">See what has a practice question, what you have answered and what needs another look. Counts use each question’s primary objective. Related tags do not fill a gap. Each question samples part of an objective; a correct answer does not prove the entire objective is mastered. Blanks in completed exams count as missed tasks for practice.</p></div><button className="action-secondary self-start" onClick={onGenerate}>Practise gaps and recent misses</button></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 text-sm">
      {[[`${knowledge.filter(r=>r.available>0).length} / ${knowledge.length}`,'Objectives with a written question'],[`${knowledge.filter(r=>r.assessed>0).length} / ${knowledge.length}`,'Objectives you have sampled'],[knowledge.filter(r=>r.missed>0).length,'Entries with a missed answer'],[skills.length,'Examination / procedure entries']].map(([n,label])=><div key={String(label)} className="bg-slate-50 rounded-xl p-4"><p className="text-2xl font-semibold text-slate-900">{n}</p><p className="text-slate-600 mt-1">{label}</p></div>)}
    </div>
    <div className="flex flex-wrap gap-3"><label className="sr-only" htmlFor="objective-filter">Filter objectives</label><select id="objective-filter" className="border rounded-lg p-2 bg-white text-sm" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All objectives</option><option value="untested">Not yet tested</option><option value="missed">Missed at least once</option><option value="gaps">No question yet</option><option value="skills">Examination and procedures</option></select><label className="sr-only" htmlFor="objective-search">Search objectives</label><input id="objective-search" className="border rounded-lg p-2 text-sm flex-1 min-w-0" placeholder="Search a topic or objective…" value={search} onChange={e=>setSearch(e.target.value)}/></div>
    <div className="space-y-2 max-h-[32rem] overflow-auto pr-1">{buckets.map(id=>{const rs=visible.filter(r=>r.bucketId===id);return <details key={id} className="border border-slate-200 rounded-xl p-4"><summary className="cursor-pointer text-sm font-medium">{rs[0].bucket}<span className="ml-2 text-slate-500 font-normal">{rs.length} entries · {rs.filter(r=>r.assessed>0).length} sampled</span></summary><ul className="mt-4 space-y-4">{rs.map(r=><li key={r.id} className="text-sm border-t pt-3"><p className="font-medium text-slate-900">{r.id} · {r.topic}</p><p className="mt-1 text-slate-600 leading-relaxed">{r.text}</p><p className={`mt-2 text-xs ${r.missed?'text-amber-800':'text-slate-500'}`}>{`${r.available} distinct bank question${r.available===1?'':'s'} · ${r.answered} answered · ${r.correct} correct · ${r.missed} missed (${r.blank} blank)${r.assessed===0?' · Not yet assessed':''}`}</p>{r.skill&&<p className="mt-1 text-xs text-slate-500">Written knowledge is tracked here. Practical performance needs direct observation.</p>}</li>)}</ul></details>;})}{!visible.length&&<p className="text-sm text-slate-500">No objectives match this filter.</p>}</div>
  </section>;
}
