import React, {useEffect,useRef,useState} from 'react';
import {ArrowRight,BookOpen,CheckCircle2,Download,FileUp,Play,Share2,Sparkles} from 'lucide-react';
import type {Project,SavedExam} from '../types';
import {parseProjectExam,addExam,mergePracticeBackup,downloadText,projectShare,emptyExam} from '../services/projectWorkflow';
import WorkspaceDialog from './WorkspaceDialog';

type Props={project:Project;onUpdate:(p:Project)=>void;onStart:(e:SavedExam)=>void;onError:(s:string)=>void;onGenerate:()=>void;onResume:()=>void;onMaterials:()=>void;onProgress:()=>void;onActionConsumed:()=>void;disabled:boolean;initialAction?:'share'|'import'};
export default function ProjectExamTools({project,onUpdate,onStart,onError,onGenerate,onResume,onMaterials,onProgress,onActionConsumed,disabled,initialAction}:Props) {
  useEffect(()=>{if(initialAction)onActionConsumed();},[]);
  const file=useRef<HTMLInputElement>(null),backup=useRef<HTMLInputElement>(null);
  const [dialog,setDialog]=useState<'import'|'share'|null>(initialAction||null);
  const [paste,setPaste]=useState(''),[showPaste,setShowPaste]=useState(false),[notice,setNotice]=useState(''),[importError,setImportError]=useState('');
  const [shareSources,setShareSources]=useState(true),[shareExams,setShareExams]=useState(true),[downloaded,setDownloaded]=useState(false),[copied,setCopied]=useState(false);
  const active=project.activeExam.questions.length>0&&project.activeExam.status==='active';
  const banks=(project.savedExams||[]).filter(e=>!e.retired);
  const materialCount=project.learningObjectivesFiles.length+project.blueprint.reduce((n,s)=>n+s.files.length,0);
  const importText=(text:string)=>{
    try {
      if(disabled)return;
      const data=JSON.parse(text.trim().replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,''));
      if(data.format==='medexam-project'||data.format==='medexam-project-backup')throw new Error('This is a whole project. Go back to My projects and choose Import project.');
      const exam=parseProjectExam(data,project.registry),next=addExam(project,exam);
      onUpdate(next);setPaste('');setShowPaste(false);setDialog(null);setImportError('');onError('');
      setNotice(next===project?'This exam is already in your library.':`${exam.title} is ready. Choose Start exam below when you want the timer to begin.`);
    }catch(e){setImportError((e as Error).message);}
  };
  const load=async(e:React.ChangeEvent<HTMLInputElement>,isBackup=false)=>{
    const f=e.target.files?.[0];e.target.value='';if(!f)return;
    if(f.size>20*1024*1024){setImportError('Choose a file under 20 MB.');return;}
    try{const text=await f.text();if(isBackup){onUpdate(mergePracticeBackup(project,JSON.parse(text)));setNotice('Practice history restored. Existing attempts were kept.');}else importText(text);}catch(err){onError((err as Error).message);}
  };
  const friendMessage=`I’m sharing ${project.name}.\n1. Open ${typeof window==='undefined'?'https://med-exam-generator.vercel.app':window.location.origin}/?import=project\n2. Sign in, then choose Import project and select the attached .medexam file. You can also try it without an account.\n3. Choose an exam, then Start exam. You get your own answers, timer and results.\nBuilt-in AI availability depends on account access and the service’s quota.`;
  return <div className="space-y-7 print:hidden">
    <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7">
      <h2 className="text-2xl font-semibold tracking-tight">Create an exam</h2>
      <p className="mt-2 text-slate-600 leading-relaxed">Generate from your study materials, or import a question file.</p>
      <div className="flex flex-wrap gap-3 mt-5"><button className="action-primary w-full sm:w-auto" disabled={disabled} onClick={onGenerate}><Sparkles className="w-4 h-4"/>Generate an exam</button><button className="action-secondary flex-1 sm:flex-none" disabled={disabled} onClick={()=>{setDialog('import');setImportError('');}}><FileUp className="w-4 h-4"/>Import an exam</button><button className="action-secondary flex-1 sm:flex-none" onClick={()=>{setDialog('share');setDownloaded(false);setCopied(false);}}><Share2 className="w-4 h-4"/>Share project</button></div>
      <div className="flex flex-wrap gap-x-5 gap-y-2 mt-5 pt-4 border-t text-sm text-slate-500"><span>{banks.length} saved {banks.length===1?'exam':'exams'}</span><span>{project.examHistory.length} completed {project.examHistory.length===1?'attempt':'attempts'}</span><button onClick={onMaterials} className="text-blue-700 hover:underline">{materialCount} study {materialCount===1?'file':'files'} · Manage materials</button></div>
    </section>
    {notice&&<p role="status" className="flex items-start gap-2 p-4 rounded-xl bg-blue-50 text-blue-900"><CheckCircle2 className="w-5 h-5 shrink-0"/>{notice}</p>}
    {active&&<section className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-blue-200 bg-blue-50 p-5"><div><h3 className="font-semibold">{project.activeExam.title||'Your exam'} is in progress</h3><p className="text-sm text-slate-600 mt-1">{Object.keys(project.activeExam.userAnswers).length} of {project.activeExam.questions.length} answered. {project.activeExam.endsAt?'Your timer continues while you are away.':'Your answers are saved.'}</p></div><button className="action-primary" disabled={disabled} onClick={onResume}><Play className="w-4 h-4"/>Continue exam</button><details className="w-full text-sm"><summary className="cursor-pointer text-slate-600">Start something else</summary><p className="my-3">Save this unfinished attempt without scoring it. {project.activeExam.endsAt?`This does not pause the timer. It ends at ${new Date(project.activeExam.endsAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}; returning after that submits the saved answers.`:'This older attempt has no timer.'}</p><button className="action-secondary" disabled={disabled} onClick={()=>onUpdate({...project,archivedExams:[...(project.archivedExams||[]),{...project.activeExam,attemptId:project.activeExam.attemptId||crypto.randomUUID()}],activeExam:{...emptyExam(),selectedSectionIds:project.activeExam.selectedSectionIds}})}>Save unfinished attempt</button></details></section>}
    {(banks.length>0||(!active&&!project.examHistory.length))&&<section aria-labelledby="exam-library-heading">
      <div className="flex flex-wrap justify-between gap-3 items-center mb-4"><h2 id="exam-library-heading" className="text-xl font-semibold tracking-tight">Your exams</h2>{project.activeExam.status==='completed'&&project.activeExam.questions.length>0&&<button onClick={onResume} className="text-sm text-blue-700 font-medium hover:underline">Review last attempt <ArrowRight className="w-4 h-4 inline"/></button>}</div>
      {!banks.length&&!project.examHistory.length?<div className="bg-white rounded-xl border border-dashed border-slate-300 p-8 text-center"><BookOpen className="w-8 h-8 text-slate-400 mx-auto mb-3"/><h3 className="font-semibold">Your next exam starts here</h3><p className="text-slate-600 mt-2 mb-5">Use Generate an exam above, or import a question file. Then start when you are ready.</p><p className="text-sm text-slate-500">{materialCount||project.registry?'Your materials are already in this project. Choose Generate to use them.':'New here? Add your objectives and notes in Study materials first.'}</p></div>:<div className="grid sm:grid-cols-2 gap-4">{banks.map(exam=>{
        const seen=new Set(project.examHistory.flatMap(a=>a.questions.map(q=>q.metadata.itemId)));
        const repeated=exam.questions.filter(q=>seen.has(q.metadata.itemId)).length;
        const isCurrent=active&&project.activeExam.examId===exam.examId;
        return <article key={exam.examId} className="bg-white rounded-xl border border-slate-200 p-5 flex flex-col gap-4"><div className="flex justify-between gap-3"><h3 className="font-semibold text-lg">{exam.title}</h3>{repeated>0&&<span className="text-xs text-slate-500 bg-slate-100 rounded-full px-2.5 py-1 self-start whitespace-nowrap">{repeated} seen before</span>}</div><p className="text-sm text-slate-600">{exam.questions.length} questions <span className="mx-2 text-slate-300">/</span> {exam.durationMinutes} {exam.durationMinutes===1?'minute':'minutes'}</p><div className="flex flex-wrap items-center justify-between gap-2 mt-auto"><button className="action-primary" aria-label={isCurrent?`Continue ${exam.title}`:`Start ${exam.title}`} disabled={disabled||(active&&!isCurrent)} onClick={()=>isCurrent?onResume():onStart(exam)}><Play className="w-4 h-4"/>{isCurrent?'Continue exam':repeated?'Retake exam':'Start exam'}</button><button className="action-quiet" onClick={()=>{downloadText(`${exam.examId}.exam.json`,JSON.stringify(exam.registry?{...exam,format:'medexam-practice'}:exam));setNotice('Exam downloaded. Send the file to your friend; they can use Import an exam inside a compatible project.');}}><Download className="w-4 h-4"/>Download exam</button></div>{active&&!isCurrent&&<p className="text-xs text-slate-500">Finish or save your current attempt first.</p>}</article>;
      })}</div>}
    </section>}
    {!!project.examHistory.length&&<section className="bg-white rounded-xl border p-5"><div className="flex flex-wrap items-center justify-between gap-3 mb-3"><h2 className="text-lg font-semibold">Previous attempts</h2><button className="action-quiet" onClick={onProgress}>Review answers and progress <ArrowRight className="w-4 h-4"/></button></div>{!banks.length&&<p className="text-sm text-slate-600 mb-3">Your earlier exams and answers are here. Generate or import an exam to add a reusable set to Your exams.</p>}<ul className="divide-y">{project.examHistory.slice(-5).reverse().map(a=><li key={a.id} className="py-3 flex justify-between gap-3 text-sm"><span>{Number.isNaN(Date.parse(a.date))?'Earlier attempt':new Date(a.date).toLocaleDateString()} · {a.totalQuestions} questions</span><span>{a.score}/{a.totalQuestions} correct</span></li>)}</ul>{project.examHistory.length>5&&<p className="text-sm text-slate-500">Showing the latest 5. All {project.examHistory.length} attempts are in Progress.</p>}</section>}
    {!!project.archivedExams?.length&&<details className="bg-white border rounded-xl p-5"><summary className="cursor-pointer font-medium">Unfinished attempts ({project.archivedExams.length})</summary><p className="text-sm text-slate-500 my-3">Original timers keep running. These attempts count toward your scores only after submission.</p>{project.archivedExams.map((a,i)=><button className="action-secondary mr-2 mb-2" key={a.attemptId||i} disabled={disabled||active} onClick={()=>{onUpdate({...project,activeExam:a,archivedExams:project.archivedExams!.filter((_,j)=>i!==j)});onResume();}}>{a.endsAt&&a.endsAt<=Date.now()?'Review expired':'Resume'} {a.title||'unfinished exam'}</button>)}</details>}
    <details className="text-sm text-slate-500"><summary className="cursor-pointer">Backups and recovery</summary><div className="flex flex-wrap gap-3 mt-3"><button className="action-secondary" onClick={()=>downloadText(`${project.name}.project-backup.json`,JSON.stringify({format:'medexam-project-backup',version:1,project}))}>Download private backup</button><button className="action-secondary" disabled={disabled} onClick={()=>backup.current?.click()}>Restore practice history</button></div><p className="mt-3">Private backups include your answers and progress. Use Share project to send study materials to a friend.</p></details>
    <input aria-label="Import exam file" ref={file} type="file" accept=".json" hidden onChange={e=>load(e)}/><input aria-label="Restore practice history file" ref={backup} type="file" accept=".json" hidden onChange={e=>load(e,true)}/>
    {dialog==='import'&&<WorkspaceDialog title="Import an exam" onClose={()=>setDialog(null)}><p className="text-slate-600 mb-5">Add a question file from a friend, Codex or Claude. Your existing exams and progress stay here.</p>{importError&&<p role="alert" className="text-red-700 bg-red-50 p-3 rounded mb-4">{importError}</p>}<button className="action-primary w-full" disabled={disabled} onClick={()=>file.current?.click()}><FileUp className="w-4 h-4"/>Choose exam file</button><p className="text-sm text-slate-500 mt-2">Accepts .json exam files, up to 20 MB.</p><button className="text-sm text-blue-700 mt-5 hover:underline" onClick={()=>setShowPaste(!showPaste)}>Have text instead? Paste an exam</button>{showPaste&&<div className="mt-3"><label className="text-sm font-medium" htmlFor="exam-paste">Paste the JSON returned by your AI</label><textarea id="exam-paste" className="w-full border rounded-lg p-3 font-mono text-sm mt-2" rows={7} value={paste} onChange={e=>setPaste(e.target.value)}/><button className="action-primary mt-3" disabled={disabled||!paste.trim()} onClick={()=>importText(paste)}>Add exam to project</button></div>}</WorkspaceDialog>}
    {dialog==='share'&&<WorkspaceDialog title="Share project" onClose={()=>setDialog(null)}><p className="text-slate-600 leading-relaxed">Give your friend a copy of <strong>{project.name}</strong>. They get their own progress; your answers and scores are not included.</p><div className="bg-slate-50 border rounded-xl p-4 my-5 text-sm"><p>{shareExams?`${banks.length} ${banks.length===1?'exam':'exams'}`:'No exams'} · {shareSources?'Study materials and exam examples included':'Reference files excluded'} · Objectives and question-writing instructions</p></div><details className="text-sm mb-5"><summary className="cursor-pointer text-slate-600">Choose what to include</summary><label className="flex items-center gap-2 mt-3"><input type="checkbox" checked={shareSources} onChange={e=>setShareSources(e.target.checked)}/>Study materials and exam examples</label><label className="flex items-center gap-2 mt-3"><input type="checkbox" checked={shareExams} onChange={e=>setShareExams(e.target.checked)}/>Saved exams and answer keys</label></details><button className="action-primary w-full" onClick={()=>{downloadText(`${project.name}.medexam`,JSON.stringify(projectShare(project,shareSources,shareExams)));setDownloaded(true);}}><Download className="w-4 h-4"/>{downloaded?'Download again':'1. Download project file'}</button><p className="text-sm text-slate-600 mt-4">2. Send that file with these instructions:</p><textarea aria-label="Instructions for your friend" readOnly className="w-full border rounded-lg bg-slate-50 p-3 text-sm leading-relaxed mt-2" rows={7} value={friendMessage}/><button className="action-secondary mt-3" onClick={async()=>{try{await navigator.clipboard.writeText(friendMessage);setCopied(true);}catch{setCopied(false);}}}>{copied?'Instructions copied':'Copy instructions'}</button><p className="text-xs text-slate-500 mt-4">This downloads a file. It does not make your project public or automatically send it to anyone.</p></WorkspaceDialog>}
  </div>;
}
